{% set name = "idna_ssl" %}
{% set version = "1.0.1" %}
{% set sha256 = "1293f030bc608e9aa9cdee72aa93c1521bbb9c7698068c61c9ada6772162b979" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5,<3.7
    - pip
  run:
    - python >=3.5,<3.7
    - idna

test:
  imports:
    - idna_ssl

about:
  home: https://github.com/aio-libs/idna-ssl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Patch ssl.match_hostname for Unicode(idna) domains support'

  dev_url: https://github.com/aio-libs/idna-ssl

extra:
  recipe-maintainers:
    - sodre
