travis:
  secure:
    BINSTAR_TOKEN: WZaK0DqkP9OIb6L+DYmwntIiLjXEVJKmLiIwyu7ariptZ7bW2k1UEI2fRX0iFkG7QQP0B/Cp71+BBbEjqz0yaJGC0XXt5hA05f6Io69N0cIWTwoOHumyJvvJXV8as5NrtNzw430s9jCo8DSlRBXFYwxTzn11kYub0ra7d3o2mIiudHOKY8GIO14BeXAb1ZgEwFjL5qviMVKYI43ghfgeNHqFlIkzuAOkTpPxNl8olWSu6Yr6fgVoKopAWZD+Z3nBG09T8s6+7GHkUv0hsHI9N3C4fyoQFGCvcIWHixWXKY/blMZpDf+E7IvuWLV4VSOiYJLBT+ZWWcNUpShN/GZTu53//8Mav21g2bkI19ML8cww4AX9NsrjWHaUag9x4F5s6KhwoVE/HWgecHQ3UWruU3nM3lWhtvmSb4OZMg8cWfcUJECut6Id5tzze40JD/Q63zSZYVnHPjMiDuuHkjnLmppRwfOnja29n1HQ1RoG71nCIHdrcA0m/+yhN0iFx/wcQ5GJ3juQSiBX8ZFRWLQPjPJkYfOt8IQmvGlWwtELBeBCaShgYU7LojTObFJeobsW+89MtN+sHAyWJdormqNUXdvOFjqXIs0H6xEEqjcCSZbXqVTWLsfTMm6m7DNAkjAHABSkn7Jne1/zlHIHKpWLQ8LUzZ0acnT60T4QTcB12sI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
